// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALokmKGIRAWhBtCwJwKwrMCk0IbHDCXRM',
    appId: '1:955982002729:web:b33490b200294bca70ba38',
    messagingSenderId: '955982002729',
    projectId: 'actividad1-5d999',
    authDomain: 'actividad1-5d999.firebaseapp.com',
    storageBucket: 'actividad1-5d999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgeW95J71i3ly4vJ75wiDikg-2aJSRPg',
    appId: '1:955982002729:android:ba412aec3428693e70ba38',
    messagingSenderId: '955982002729',
    projectId: 'actividad1-5d999',
    storageBucket: 'actividad1-5d999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVA-atMWEsiWjukKUBD8hVq7BQRkRx-8c',
    appId: '1:955982002729:ios:4cae661dd6c70aa170ba38',
    messagingSenderId: '955982002729',
    projectId: 'actividad1-5d999',
    storageBucket: 'actividad1-5d999.appspot.com',
    iosBundleId: 'com.example.practica1v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVA-atMWEsiWjukKUBD8hVq7BQRkRx-8c',
    appId: '1:955982002729:ios:4cae661dd6c70aa170ba38',
    messagingSenderId: '955982002729',
    projectId: 'actividad1-5d999',
    storageBucket: 'actividad1-5d999.appspot.com',
    iosBundleId: 'com.example.practica1v2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALokmKGIRAWhBtCwJwKwrMCk0IbHDCXRM',
    appId: '1:955982002729:web:27ef887173107ded70ba38',
    messagingSenderId: '955982002729',
    projectId: 'actividad1-5d999',
    authDomain: 'actividad1-5d999.firebaseapp.com',
    storageBucket: 'actividad1-5d999.appspot.com',
  );
}
